# Generated by Django 4.2.9 on 2024-02-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "simpleapp",
            "0003_remove_post_category_alter_post_item_postcategory_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
