# Generated by Django 4.2.9 on 2024-01-22 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                (
                    "item",
                    models.CharField(
                        choices=[("ART", "Статья"), ("NEW", "Новость")],
                        default="ART",
                        max_length=3,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("heading", models.CharField(max_length=255)),
                ("text", models.TextField(default="Текст не введен")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post",
                        to="simpleapp.category",
                    ),
                ),
            ],
        ),
    ]
